apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selfops-ingress
  namespace: platform
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: "app.89.167.95.204.nip.io"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: selfops-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: selfops-frontend
                port:
                  number: 3000
